FROM node:22.17.1-alpine

# RUN npm install yarn -g

WORKDIR /app

COPY ../package*.json ./

RUN npm install --legacy-peer-deps

COPY ../ .

RUN npm run build

ENV NODE_ENV production

ENV TZ=Asia/Jakarta

EXPOSE 3000

CMD ["npm", "start"]