worker_processes 1;

events {
  worker_connections 1024;
}

http {
  # Server block untuk akses internal (dari Cloudflare tunnel)
  server {
    listen 80 default_server;

    location / {
      proxy_pass http://app:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # Disable buffering
      proxy_buffering off;
    }
  }
}